# Generated by Django 2.2.5 on 2020-03-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('result', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Remedies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=256)),
                ('remedy', models.CharField(max_length=256)),
                ('cause', models.CharField(max_length=256)),
                ('symptom', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Remedies',
            },
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
