# Generated by Django 2.2.5 on 2020-03-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_auto_20200304_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remedies',
            old_name='cause',
            new_name='cause_1',
        ),
        migrations.RenameField(
            model_name='remedies',
            old_name='remedy',
            new_name='cause_2',
        ),
        migrations.RenameField(
            model_name='remedies',
            old_name='symptom',
            new_name='cause_3',
        ),
        migrations.AddField(
            model_name='remedies',
            name='remedy_1',
            field=models.CharField(default=1212, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedies',
            name='remedy_2',
            field=models.CharField(default=1212, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedies',
            name='remedy_3',
            field=models.CharField(default=121212, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedies',
            name='symptom_1',
            field=models.CharField(default=1212, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedies',
            name='symptom_2',
            field=models.CharField(default=1212, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedies',
            name='symptom_3',
            field=models.CharField(default=1212, max_length=256),
            preserve_default=False,
        ),
    ]
