# Generated by Django 2.2.5 on 2020-03-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0003_auto_20200308_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedies',
            name='cause_1',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='cause_2',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='cause_3',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='remedy_1',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='remedy_2',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='remedy_3',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='symptom_1',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='symptom_2',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='symptom_3',
            field=models.CharField(max_length=1024),
        ),
    ]
