# Generated by Django 2.2.5 on 2020-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0004_auto_20200309_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('feed', models.CharField(max_length=1000)),
            ],
        ),
    ]
