# Generated by Django 2.2.5 on 2020-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0007_auto_20200403_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedies',
            name='cause_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='cause_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='cause_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='remedy_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='remedy_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='remedy_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='symptom_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='symptom_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='remedies',
            name='symptom_3',
            field=models.TextField(),
        ),
    ]
