# Generated by Django 2.2.5 on 2020-04-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0008_auto_20200409_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feed',
            field=models.TextField(),
        ),
    ]
