from django.urls import path
from . import views
from django.contrib.auth.views import (PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
PasswordResetCompleteView)

urlpatterns = [
    path('', views.main, name = 'leafy-home'),
    path('detection/', views.index, name = 'user-detection'),
    path('detection/fullResult/<str:result>/', views.fullResult, name = 'fullResult'),
    path('feedback/', views.feedback, name = 'user-feedback'),
    path('faq/', views.faq, name = 'faq-home'),
    path('info/', views.info, name = 'info'),
    path('getans/<int:id>/',views.getans, name = 'getans'),
    path('postans/<int:id>/',views.postans, name = 'postans'),
    path('login/',views.loginUser, name = 'login'),
    path('logout/',views.logoutUser ,name = 'logout'),
    path('reg/',views.reg, name = 'reg'),
    path('postquestion/', views.postqn, name = 'postquestion'),
    path('profile/',views.profile, name = 'profile'),
    path('edit/<int:id>/', views.editqn, name = 'edit-qn'),
    path('editans/<int:id>/', views.editans, name = 'edit-an'),
    path('deleteqn/<int:id>/', views.deleteqn, name = 'delete-qn'),
    path('deleteans/<int:id>/', views.deleteans, name = 'delete-an'),
    path('editProfile/', views.editProfile, name = 'editProfile'),
    path('deleteProfile/', views.deleteProfile, name = 'deleteProfile'),
    path('password-reset/', PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    # path('chat/', views.chat),
    path('aadmin/', views.aadmin, name = 'admin'),
    path('sendMail/', views.sendMail, name = 'sendMail'),
    path('adminUserPosts/', views.adminUserPosts, name = 'adminUserPosts'),
    path('adminTags/', views.adminTags, name = 'adminTags'),
    path('adminFeedback/', views.adminFeedback, name = 'adminFeedback'),
    path('adminRemedies/', views.adminRemedies, name = 'adminRemedies'),
    path('adminImages/', views.adminImages, name = 'adminImages'),

    path('addtag/', views.addtag, name = 'addTag'),
    path('editTag/<int:id>/', views.editTag, name = 'editTag'),
    path('addRemedy/', views.addRemedy, name = 'addRemedy'),
    path('editRemedy/<int:id>/', views.editRemedy,name = 'editRemedy'),
    path('delRemedy/<int:id>/', views.delRemedy, name = 'delRemedy'),
    path('delhist/<int:id>/', views.delhist, name = 'delHistory'),
    path('deltag/<int:id>', views.deltag, name = 'delTag'),
    path('delFeed/<int:id>/', views.delFeed, name = 'delFeedback'),
    path('Ablock/<int:id>/', views.Ablock, name = 'userBlock'),
    path('changeExpert/<int:id>/', views.changeExpert, name = 'changeExpert'),
    path('Aunblock/<int:id>/', views.Aunblock, name = 'userUnblock'),
    path('Adel/<str:id>/', views.Adel, name = 'userDelete'),
    path('changeRole/<int:id>/', views.changeRole, name = 'changeRole'),
    path('admindeleteqn/<int:id>/', views.admindeleteqn, name = 'adminDelq'),
    path('admindeleteans/<int:id>/', views.admindeleteans, name = 'adminDela'),
]